Repository OpenVicProject/OpenVic, pull requests merged in 2023-05, with the labels that each got.

#99 Add some license conformance for Godot
  game/src/CreditsMenu/CreditsMenu.gd
  game/src/CreditsMenu/CreditsMenu.tscn
  game/src/CreditsMenu/GodotEngineButton.gd
  game/src/CreditsMenu/GodotEngineButton.tscn
  game/src/CreditsMenu/logo_vertical_color_dark.svg
  game/src/CreditsMenu/logo_vertical_color_dark.svg.import
Labels: enhancement

#102 Add ArgumentParser
  game/project.godot
  game/src/ArgumentOption.gd
  game/src/ArgumentParser.gd
  game/src/ArgumentParser.tscn
  game/src/GameStart.tscn
Labels: enhancement

#104 Better province highlight on selection/hover.
  game/src/GameSession/GameSession.tscn
  game/src/GameSession/MapView.gd
  game/src/GameSession/ProvinceOverviewPanel.gd
  game/src/GameSession/ProvinceOverviewPanel.tscn
  game/src/GameSession/TerrainMap.gdshader
Labels: enhancement, ui functionality, map

#105 Fix display names for North American provinces
  game/localisation/en_GB/provinces.csv
Labels: bug

#109 Add UI scaling through menu option
  game/localisation/en_GB/menus.csv
  game/localisation/en_US/menus.csv
  game/localisation/fr_FR/menus.csv
  game/project.godot
  game/src/Autoload/GuiScale.gd
  game/src/Autoload/Resolution.gd
  game/src/GameSession/MapView.gd
  game/src/OptionMenu/GuiScaleSelector.gd
  game/src/OptionMenu/VideoTab.tscn
Labels: enhancement, requirement ui, requirement ui functionality

#108 Add clarification on licensing of artistic works
  LICENSE-EXCEPTIONS.md
Labels: documentation, enhancement

#110 Add Save/Load Menu, save loading to LobbyMenu, and file saving
  game/localisation/en_GB/menus.csv
  game/project.godot
  game/src/Autoload/SaveManager.gd
  game/src/GameMenu.tscn
  game/src/GameSession/GameSession.tscn
  game/src/GameSession/GameSessionMenu.gd
  game/src/GameSession/GameSessionMenu.tscn
  game/src/LobbyMenu/LobbyMenu.gd
  game/src/LobbyMenu/LobbyMenu.tscn
  game/src/LobbyMenu/LobbyPanelButton.gd
  game/src/LobbyMenu/LobbyPanelButton.tscn
  game/src/SaveLoadMenu/SaveLoadMenu.gd
  game/src/SaveLoadMenu/SaveLoadMenu.tscn
  game/src/SaveLoadMenu/SavePanelButton.gd
  game/src/SaveLoadMenu/SavePanelButton.tscn
  game/src/SaveLoadMenu/SaveResource.gd
  game/theme/default_theme.tres
  game/theme/game_session_menu.tres
Labels: enhancement, requirement ui, requirement ui functionality

#112 Fix incomplete #110 requirement documentation
  game/src/LobbyMenu/LobbyMenu.gd
  game/src/LobbyMenu/LobbyMenu.tscn
  game/src/LobbyMenu/LobbyPanelButton.tscn
  game/src/SaveLoadMenu/SaveLoadMenu.gd
  game/src/SaveLoadMenu/SavePanelButton.tscn
Labels: bug, documentation

#114 Update README to reflect project name change.
  README.md
Labels: documentation

#115 Fix SettingHSlider not loading properly on default values
  game/src/MusicConductor/MusicConductor.tscn
  game/src/OptionMenu/SettingNodes/SettingHSlider.gd
Labels: bug, requirement ui functionality, requirement sound

#113 Add Keep Resolution Dialog
  game/localisation/en_GB/menus.csv
  game/localisation/en_US/menus.csv
  game/localisation/fr_FR/menus.csv
  game/src/GameSession/GameSession.tscn
  game/src/OptionMenu/ResolutionSelector.gd
  game/src/OptionMenu/VideoTab.tscn
Labels: enhancement, requirement ui, requirement ui functionality

#118 Added Grain & Wool RGO icons
  game/art/economy/goods/good_grain.png
  game/art/economy/goods/good_wool.png
Labels: enhancement, requirement ui

#120 Add revert dialog functionality to ScreenModeSelector
  game/src/Autoload/Resolution.gd
  game/src/OptionMenu/GeneralTab.tscn
  game/src/OptionMenu/GuiScaleSelector.gd
  game/src/OptionMenu/MonitorDisplaySelector.gd
  game/src/OptionMenu/ResolutionRevertDialog.gd
  game/src/OptionMenu/ResolutionSelector.gd
  game/src/OptionMenu/ScreenModeSelector.gd
  game/src/OptionMenu/SettingNodes/SettingOptionButton.gd
  game/src/OptionMenu/SettingNodes/SettingRevertButton.gd
  game/src/OptionMenu/VideoTab.tscn
Labels: bug, enhancement

#122 Update Godot link to latest stable release
  docs/contribution-quickstart-guide.md
Labels: bug, documentation

#126 Added requirement comments
  extension/src/Checksum.hpp
  game/art/economy/goods/README.md
  game/src/GameSession/MapControlPanel/MapControlPanel.tscn
  game/src/MusicConductor/MusicConductor.gd
  game/src/MusicConductor/MusicPlayer.gd
  game/src/OptionMenu/GeneralTab.tscn
  game/src/OptionMenu/VideoTab.tscn
Labels: documentation, enhancement, requirement ui, requirement ui functionality, requirement filesystem, requirement sound, requirement dataloading

#127 Fix Github Actions for release
  .github/workflows/builds.yml
Labels: enhancement, meta
