Repository OpenVicProject/OpenVic, pull requests merged in 2023-02, with the labels that each got.

#15 Add Keychain plugin for Controls tab
  game/addons/keychain/Keychain.gd
  game/addons/keychain/LICENSE
  game/addons/keychain/ShortcutEdit.gd
  game/addons/keychain/ShortcutEdit.tscn
  game/addons/keychain/ShortcutProfile.gd
  game/addons/keychain/ShortcutSelectorDialog.gd
  game/addons/keychain/ShortcutSelectorDialog.tscn
  game/addons/keychain/assets/add.svg
  game/addons/keychain/assets/add.svg.import
  game/addons/keychain/assets/close.svg
  game/addons/keychain/assets/close.svg.import
  game/addons/keychain/assets/edit.svg
  game/addons/keychain/assets/edit.svg.import
  game/addons/keychain/assets/folder.svg
  game/addons/keychain/assets/folder.svg.import
  game/addons/keychain/assets/joy_axis.svg
  game/addons/keychain/assets/joy_axis.svg.import
  game/addons/keychain/assets/joy_button.svg
  game/addons/keychain/assets/joy_button.svg.import
  game/addons/keychain/assets/keyboard.svg
  game/addons/keychain/assets/keyboard.svg.import
  game/addons/keychain/assets/keyboard_physical.svg
  game/addons/keychain/assets/keyboard_physical.svg.import
  game/addons/keychain/assets/mouse.svg
  game/addons/keychain/assets/mouse.svg.import
  game/addons/keychain/assets/shortcut.svg
  game/addons/keychain/assets/shortcut.svg.import
  game/addons/keychain/plugin.cfg
  game/addons/keychain/plugin.gd
  game/addons/keychain/profiles/default.tres
  game/addons/keychain/translations/README.md
  game/addons/keychain/translations/Translations.pot
  game/addons/keychain/translations/el_GR.po
  game/project.godot
  game/src/Autoload/Events.gd
  game/src/Autoload/Events/Options.gd
  game/src/Autoload/Resolution.gd
  game/src/GameMenu.gd
  game/src/LocaleButton.gd
  game/src/OptionMenu/ControlsTab.tscn
  game/src/OptionMenu/MonitorDisplaySelector.gd
  game/src/OptionMenu/OptionsMenu.gd
  game/src/OptionMenu/OptionsMenu.tscn
  game/src/OptionMenu/OtherTab.tscn
  game/src/OptionMenu/ResolutionSelector.gd
  game/src/OptionMenu/ScreenModeSelector.gd
  game/src/OptionMenu/SettingNodes/SettingHSlider.gd
  game/src/OptionMenu/SettingNodes/SettingOptionButton.gd
  game/src/OptionMenu/SoundTab.gd
  game/src/OptionMenu/SoundTab.tscn
  game/src/OptionMenu/VideoTab.tscn
Labels: enhancement, ui, ui functionality

#17 Delete Simulation singleton correctly.
  extension/src/register_types.cpp
Labels: bug

#25 Add Sound Effect Manager
  game/audio/sfx/click.ogg
  game/audio/sfx/click.ogg.import
  game/project.godot
  game/src/Autoload/SFX.gd
  game/src/MainMenu/MainMenu.gd
Labels: enhancement, ui, sound

#21 Add Setting Sanatization
  game/src/Autoload/Events/Options.gd
  game/src/Autoload/Resolution.gd
  game/src/LocaleButton.gd
  game/src/OptionMenu/MonitorDisplaySelector.gd
  game/src/OptionMenu/OptionsMenu.gd
  game/src/OptionMenu/ResolutionSelector.gd
  game/src/OptionMenu/ScreenModeSelector.gd
  game/src/OptionMenu/SettingNodes/SettingHSlider.gd
  game/src/OptionMenu/SettingNodes/SettingOptionButton.gd
  game/src/OptionMenu/VideoTab.tscn
  game/src/OptionMenu/VolumeGrid.gd
Labels: enhancement, ui, ui functionality

#26 Add skeleton for Game Lobby Menu
  game/src/GameMenu.gd
  game/src/GameMenu.tscn
  game/src/LobbyMenu/LobbyMenu.gd
  game/src/LobbyMenu/LobbyMenu.tscn
  game/src/MainMenu/MainMenu.gd
Labels: enhancement, ui

#3 Add MacOS template
  .gitignore
  game/export/osx/.gitignore
  game/export_presets.cfg
Labels: enhancement, macos

#45 Refactor SFX into a SoundManager
  game/addons/kenney_ui_audio/LICENSE.txt
  game/addons/kenney_ui_audio/click3.wav
  game/addons/kenney_ui_audio/click3.wav.import
  game/default_theme.theme
  game/project.godot
  game/src/Autoload/SFX.gd
  game/src/Autoload/SoundManager.gd
  game/src/MainMenu/MainMenu.gd
  game/src/Utility/StyleBoxWithSound.gd
Labels: enhancement, ui, sound
