Repository OpenVicProject/OpenVic, pull requests merged in 2023-03, with the labels that each got.

#16 Add Credits System
  .gitignore
  game/common/credits.csv
  game/common/credits.csv.import
  game/src/Credits/Credits.gd
  game/src/Credits/Credits.tscn
  game/src/Credits/PersonLabelSettings.tres
  game/src/Credits/ProjectLabelSettings.tres
  game/src/Credits/RoleLabelSettings.tres
  game/src/GameMenu.gd
  game/src/GameMenu.tscn
  game/src/MainMenu/MainMenu.gd
  game/src/MainMenu/MainMenu.tscn
Labels: enhancement, ui, ui functionality

#43 Update Keychain SVG imports to Godot 4 RC 5
  game/addons/keychain/assets/add.svg.import
  game/addons/keychain/assets/close.svg.import
  game/addons/keychain/assets/edit.svg.import
  game/addons/keychain/assets/folder.svg.import
  game/addons/keychain/assets/joy_axis.svg.import
  game/addons/keychain/assets/joy_button.svg.import
  game/addons/keychain/assets/keyboard.svg.import
  game/addons/keychain/assets/keyboard_physical.svg.import
  game/addons/keychain/assets/mouse.svg.import
  game/addons/keychain/assets/shortcut.svg.import
Labels: enhancement

#48 Make default_theme a text resource
  game/default_theme.theme
  game/default_theme.tres
  game/src/MainMenu/MainMenu.tscn
Labels: enhancement, ui

#52 Make LobbyMenu resolution independent and fix MacOS export directory
  game/export/MacOS/.gitignore
  game/export_presets.cfg
  game/src/LobbyMenu/LobbyMenu.gd
  game/src/LobbyMenu/LobbyMenu.tscn
Labels: bug, ui, macos

#53 Credits loading sanatization
  game/common/credits.csv
  game/src/Credits/Credits.gd
Labels: enhancement, ui, ui functionality

#14 Modify Project Structure Documentation
  docs/project-file-structure.md
Labels: documentation

#51 Fix Credits to use theme type variants over LabelSettings
  game/default_theme.tres
  game/src/Credits/Credits.gd
  game/src/Credits/Credits.tscn
  game/src/Credits/PersonLabelSettings.tres
  game/src/Credits/ProjectLabelSettings.tres
  game/src/Credits/RoleLabelSettings.tres
  game/src/GameMenu.tscn
Labels: enhancement, ui

#58 Added Data modelling Documentation - JC and Vanilla
  docs/simulation/goods.md
  docs/simulation/ideologies.md
  docs/simulation/sim_doc_format.md
Labels: documentation, simulation

#57 Cleanup MusicPlayer for future development
  game/audio/music/Brunels_Waltz_2.mp3.import
  game/audio/music/Deliverance.mp3.import
  game/audio/music/The_Crown.mp3.import
  game/src/GameMenu.tscn
  game/src/MusicConductor/MusicConductor.gd
  game/src/MusicConductor/MusicConductor.tscn
  game/src/MusicConductor/MusicPlayer.gd
  game/src/MusicConductor/MusicPlayer.tscn
  game/src/MusicConductor/MusicUIController.gd
  game/src/MusicConductor/MusicUIController.tscn
  game/src/MusicConductor/SongInfo.gd
  game/src/OptionMenu/OptionsMenu.tscn
Labels: enhancement, ui, ui functionality, sound

#62 Fix MusicConductor not loading music on exported executables
  game/src/MusicConductor/MusicConductor.gd
Labels: bug, confirmed

#61 Make PR Continuous Integration work
  .github/workflows/builds.yml
Labels: enhancement, build

#60 Add Debug Mode
  game/project.godot
  game/src/Autoload/GameDebug.gd
Labels: enhancement

#54 Polishing and Adding to Options Menu
  game/src/GameMenu.gd
  game/src/GameMenu.tscn
  game/src/LocaleButton.gd
  game/src/MainMenu/MainMenu.gd
  game/src/MainMenu/MainMenu.tscn
  game/src/OptionMenu/AutosaveIntervalSelector.gd
  game/src/OptionMenu/GeneralTab.gd
  game/src/OptionMenu/GeneralTab.tscn
  game/src/OptionMenu/OptionsMenu.gd
  game/src/OptionMenu/OptionsMenu.tscn
  game/src/OptionMenu/QualityPresetSelector.gd
  game/src/OptionMenu/RefreshRateSelector.gd
  game/src/OptionMenu/VideoTab.gd
  game/src/OptionMenu/VideoTab.tscn
Labels: enhancement, ui, ui functionality

#59 Add Splash Startup functionality
  game/project.godot
  game/splash_assets/splash_end.png
  game/splash_assets/splash_end.png.import
  game/splash_assets/splash_image.png
  game/splash_assets/splash_image.png.import
  game/splash_assets/splash_startup.ogv
  game/src/GameMenu.gd
  game/src/GameStart.tscn
  game/src/SplashContainer.gd
Labels: enhancement

#65 Refactor GameMenu to rely on export variables
  game/src/GameMenu.gd
  game/src/GameMenu.tscn
Labels: enhancement

#74 Fix Export Issues
  game/common/credits.csv.import
  game/export_presets.cfg
Labels: bug, confirmed

#76 Fix Main Menu button export texture
  game/src/MainMenu/MainMenu.tscn
  game/theme/assets/main_menu_button_normal.stylebox
  game/theme/assets/main_menu_button_normal.tres
  game/theme/main_menu.tres
Labels: bug, ui

#79 Add automated Git release info retrieval on export
  .github/actions/openvic2-env/action.yml
  .github/workflows/builds.yml
  game/addons/openvic2-plugin/ReleaseExportEditorPlugin.gd
  game/addons/openvic2-plugin/openvic2-plugin.gd
  game/addons/openvic2-plugin/plugin.cfg
  game/project.godot
  game/src/GameMenu.tscn
  game/src/MainMenu/MainMenu.gd
  game/src/MainMenu/MainMenu.tscn
  game/src/MainMenu/ReleaseInfoBox.gd
  game/src/MainMenu/ReleaseInfoBox.tscn
  game/src/Utility/GIT_INFO.gd
  game/theme/main_menu.tres
Labels: enhancement, ui, ui functionality
