Repository OpenVicProject/OpenVic, pull requests merged in 2023-06, with the labels that each got.

#129 Add environment variables for trivial Godot updates
  .github/workflows/builds.yml
Labels: enhancement, meta

#128 Russian localisation supplied by av213238
  game/localisation/ru_RU/goods.csv
  game/localisation/ru_RU/goods.csv.import
  game/localisation/ru_RU/mapmodes.csv
  game/localisation/ru_RU/mapmodes.csv.import
  game/localisation/ru_RU/menus.csv
  game/localisation/ru_RU/menus.csv.import
Labels: enhancement

#132 Basic Loading Screen
  game/common/quotes.txt
  game/src/Game/Autoload/Events.gd
  game/src/Game/Autoload/Events/GameDebug.gd
  game/src/Game/Autoload/Events/Localisation.gd
  game/src/Game/Autoload/Events/Options.gd
  game/src/Game/Autoload/Events/ShaderManager.gd
  game/src/Game/GameMenu.gd
  game/src/Game/GameStart.tscn
  game/src/Game/LoadingScreen.gd
  game/src/Game/LoadingScreen.tscn
  game/theme/assets/loading_screen.png
  game/theme/assets/loading_screen.png.import
Labels: enhancement, requirement ui, requirement ui functionality, requirement filesystem

#133 Fix ArgumentParser excluding last character for arg key
  game/src/Game/Autoload/Argument/ArgumentParser.gd
  game/src/Game/Autoload/Argument/ArgumentParser.tscn
  game/src/Game/Autoload/Events.gd
  game/src/Game/Autoload/Events/GameDebug.gd
Labels: bug, enhancement, requirement system

#131 Localisation and UI focus cleanup
  extension/src/LoadLocalisation.cpp
  game/localisation/README.md
  game/localisation/en_GB/goods.csv
  game/localisation/en_GB/mapmodes.csv
  game/localisation/en_GB/menus.csv
  game/localisation/en_GB/provinces.csv
  game/localisation/en_GB/regions.csv
  game/localisation/en_US/menus.csv
  game/localisation/fr_FR/menus.csv
  game/localisation/ru_RU/goods.csv
  game/localisation/ru_RU/mapmodes.csv
  game/localisation/ru_RU/menus.csv
  game/src/Game/Autoload/Events/Localisation.gd
  game/src/Game/Autoload/Resolution.gd
  game/src/Game/GameSession/GameSpeedPanel.tscn
  game/src/Game/GameSession/MapControlPanel/MapControlPanel.gd
  game/src/Game/GameSession/MapControlPanel/MapControlPanel.tscn
  game/src/Game/GameSession/ProvinceOverviewPanel/ProvinceOverviewPanel.gd
  game/src/Game/GameSession/ProvinceOverviewPanel/ProvinceOverviewPanel.tscn
  game/src/Game/Menu/CreditsMenu/CreditsMenu.gd
  game/src/Game/Menu/MainMenu/ReleaseInfoBox.tscn
  game/src/Game/Menu/OptionMenu/MonitorDisplaySelector.gd
  game/src/Game/Menu/OptionMenu/OptionsMenu.gd
  game/src/Game/Menu/OptionMenu/OptionsMenu.tscn
  game/src/Game/Menu/OptionMenu/ResolutionSelector.gd
  game/src/Game/Menu/OptionMenu/ScreenModeSelector.gd
  game/src/Game/Menu/OptionMenu/SettingNodes/SettingCheckBox.gd
  game/src/Game/Menu/OptionMenu/SettingNodes/SettingRevertButton.gd
  game/src/Game/Menu/OptionMenu/SettingRevertDialog.gd
  game/src/Game/Menu/OptionMenu/SoundTab.gd
  game/src/Game/Menu/OptionMenu/SoundTab.tscn
  game/src/Game/Menu/OptionMenu/VideoTab.tscn
  game/src/Game/MusicConductor/MusicConductor.gd
  game/src/Game/MusicConductor/MusicConductor.tscn
  game/src/Game/MusicConductor/MusicPlayer.tscn
Labels: enhancement
