Repository OpenVicProject/OpenVic, pull requests merged in 2023-09, with the labels that each got.

#152 Update README.md for Archlinux users
  README.md
Labels: documentation, enhancement

#153 Add Window Override
  game/project.godot
  game/src/Game/Autoload/Argument/ArgumentParser.gd
  game/src/Game/Autoload/WindowOverride.gd
  game/src/Game/GameStart.gd
Labels: enhancement, needs testing

#155 Implemented zoom-to-cursor functionality
  game/src/Game/GameSession/MapView.gd
Labels: bug, enhancement, requirement map

#156 Fixup Documentation
  .vscode/launch.json
  README.md
  docs/contribution/cloning.md
  docs/contribution/debugging.md
  docs/contribution/rebasing.md
  docs/contribution/run-build-and-export.md
  docs/contribution/system-requirements.md
  docs/contribution/using-git-bisect.md
Labels: documentation, enhancement

#159 Fix incorrect run-build-and-export.md path
  README.md
Labels: bug, documentation
