Repository OpenVicProject/OpenVic, pull requests merged in 2024-12, with the labels that each got.

#314 Fix `object specified more than once` build issue
  SConstruct
Labels: bug

#311 Add tooltip for RGO_employment
  extension/src/openvic-extension/classes/GUILabel.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  game/src/Game/GameSession/ProvinceOverviewPanel.gd
Labels: enhancement

#317 Add class reference checks to Github builds workflow
  .github/workflows/builds.yml
  README.md
Labels: documentation, enhancement, meta

#318 Fix GUINode click mask low alpha threshold
  extension/src/openvic-extension/classes/GUINode.cpp
Labels: bug

#319 Add Godot sourced doc_status.py doc tool
  extension/doc_classes/GFXButtonStateTexture.xml
  extension/doc_classes/GameSingleton.xml
  extension/doc_classes/MapMesh.xml
  extension/doc_classes/MenuSingleton.xml
  extension/doc_tools/.gitignore
  extension/doc_tools/doc_status.py
  extension/doc_tools/make_rst.py
  extension/doc_tools/patches/make_rst.patch
  extension/src/openvic-extension/classes/GFXButtonStateTexture.cpp
  extension/src/openvic-extension/classes/MapMesh.cpp
  extension/src/openvic-extension/singletons/GameSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.hpp
  extension/src/openvic-extension/singletons/PopulationMenu.cpp
Labels: bug, documentation, enhancement

#327 fix sp infantry
  game/src/Game/Model/XACLoader.gd
Labels: bug

#326 Add player customizable button hotkeys
  extension/src/openvic-extension/utility/UITools.cpp
  game/addons/keychain/Keychain.gd
  game/addons/keychain/ShortcutEdit.gd
  game/addons/keychain/ShortcutEdit.tscn
  game/addons/keychain/ShortcutProfile.gd
  game/addons/keychain/assets/add.svg
  game/addons/keychain/assets/close.svg
  game/addons/keychain/assets/edit.svg
  game/addons/keychain/assets/folder.svg
  game/addons/keychain/assets/keyboard.svg
  game/addons/keychain/assets/keyboard_physical.svg
  game/addons/keychain/assets/mouse.svg
  game/addons/keychain/assets/shortcut.svg
  game/addons/keychain/translations/Translations.pot
  game/addons/keychain/translations/el_GR.po
  game/assets/localisation/locales/helpers.csv
  game/assets/localisation/locales/helpers.csv.import
  game/project.godot
  game/src/Game/GameSession/GameSession.gd
  game/src/Game/GameStart.gd
  game/src/Game/Menu/OptionMenu/OptionsMenu.gd
Labels: bug, enhancement

#330 Move keep_binding_check definition to GameStart.gd
  game/addons/keychain/Keychain.gd
  game/addons/keychain/ShortcutProfile.gd
  game/src/Game/GameStart.gd
Labels: bug

#332 Correct dependabot to focus on OpenVic submodules
  .github/dependabot.yml
Labels: bug, meta

#339 Fix default hotkeys being erroneously set
  game/src/Game/GameSession/GameSession.gd
  game/src/Game/Menu/OptionMenu/KeychainShortcutEdit.gd
  game/src/Game/Menu/OptionMenu/KeychainShortcutEdit.tscn
  game/src/Game/Menu/OptionMenu/OptionsMenu.gd
  game/src/Game/Menu/OptionMenu/OptionsMenu.tscn
Labels: bug

#341 Fix PopulationMenu's pop_list mouse_filter not being pass
  game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
Labels: bug
