Repository OpenVicProject/OpenVic, pull requests merged in 2024-02, with the labels that each got.

#204 Add workflow run limitations
  .github/workflows/builds.yml
Labels: enhancement, meta

#205 Add GameInfo button to MainMenu
  game/assets/graphics/theme/main_menu.tres
  game/assets/localisation/locales/en_GB/menus.csv
  game/assets/localisation/locales/en_US/menus.csv
  game/src/Game/Menu/MainMenu/ReleaseInfoBox.gd
  game/src/Game/Menu/MainMenu/ReleaseInfoBox.tscn
Labels: enhancement

#207 Document HR
  docs/simulation/calculations.yaml
Labels: documentation, enhancement
