Repository OpenVicProject/OpenVic, pull requests merged in 2024-09, with the labels that each got.

#257 Military score calculation
  docs/simulation/calculations.yaml
Labels: documentation

#258 Document montly literacy change
  docs/simulation/calculations.yaml
Labels: documentation

#259 Document regiment reinforcements
  docs/simulation/calculations.yaml
Labels: documentation

#264 Include admirals in leader score
  docs/simulation/calculations.yaml
Labels: documentation

#265 Correct Maximum regiments per soldier POP
  docs/simulation/calculations.yaml
Labels: documentation

#267 Explain worker pops depend on can_work_factory = yes
  docs/simulation/calculations.yaml
Labels: documentation

#269 Rename sum_workforce_in_state to total_factory_jobs_in_state
  docs/simulation/calculations.yaml
Labels: documentation

#272 music null check
  extension/src/openvic-extension/singletons/SoundSingleton.cpp
  game/src/Game/MusicConductor/MusicConductor.gd
Labels: bug

#273 Model loader Fixes
  game/src/Game/Model/XACLoader.gd
  game/src/Game/Model/XSMLoader.gd
Labels: bug

#270 Allow tooltips to be as tall as the window + shift them to stay inside it
  extension/src/openvic-extension/classes/GUILabel.cpp
  extension/src/openvic-extension/classes/GUILabel.hpp
  game/src/Game/GameSession/Tooltip.gd
Labels: enhancement

#276 Use correct play & pause music icons
  game/src/Game/MusicConductor/MusicPlayer.gd
Labels: bug
