Repository OpenVicProject/OpenVic, pull requests merged in 2024-11, with the labels that each got.

#283 Use real RGO data
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  game/src/Game/GameSession/ProvinceOverviewPanel.gd
Labels: enhancement

#291 Use Dependabot to Automatically Update Dependencies
  .github/dependabot.yml
Labels: enhancement

#203 Add issue templates
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-victoria-2-discrepency.yml
  .github/ISSUE_TEMPLATE/3-gameplay-feature-request.yml
  .github/ISSUE_TEMPLATE/4-mod-feature-request.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement, meta

#289 Fix quickstart guide to recommend scons 4.7.0
  docs/contribution-quickstart-guide.md
  docs/images/installation/godot-dl-page.png
  docs/images/installation/scons-install.png
  docs/images/proj-setup/01-git-clone-link.png
  docs/images/proj-setup/02-git-clone.png
  docs/images/proj-setup/03-submodules.png
  docs/images/proj-setup/05-scons.png
  docs/images/proj-setup/06-import.png
  docs/images/proj-setup/07-select-project.png
  docs/images/proj-setup/08-import-edit.png
  docs/images/proj-setup/09-run-project.png
Labels: documentation

#297 Document factory throttling
  docs/simulation/calculations.yaml
Labels: documentation

#301 When setting a tooltip, automatically switch mouse filter to PASS if it's IGNORE
  extension/src/openvic-extension/classes/GUIHasTooltip.hpp
  game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
  game/src/Game/GameSession/Topbar.gd
Labels: enhancement

#302 Fix resolution options text update before resolution selector is ready
  game/src/Game/Menu/OptionMenu/ResolutionSelector.gd
Labels: bug

#303 Fix `AssetManager::get_currency_texture` crashes
  extension/src/openvic-extension/singletons/AssetManager.cpp
  extension/src/openvic-extension/singletons/AssetManager.hpp
Labels: bug

#308 Add in-editor documentation support
  .gitignore
  SConstruct
  extension/doc_classes/AssetManager.xml
  extension/doc_classes/Checksum.xml
  extension/doc_classes/GFXButtonStateHavingTexture.xml
  extension/doc_classes/GFXButtonStateTexture.xml
  extension/doc_classes/GFXCorneredTileSupportingTexture.xml
  extension/doc_classes/GFXMaskedFlagTexture.xml
  extension/doc_classes/GFXPieChartTexture.xml
  extension/doc_classes/GFXSpriteTexture.xml
  extension/doc_classes/GUIButton.xml
  extension/doc_classes/GUIIcon.xml
  extension/doc_classes/GUIIconButton.xml
  extension/doc_classes/GUILabel.xml
  extension/doc_classes/GUIListBox.xml
  extension/doc_classes/GUIMaskedFlag.xml
  extension/doc_classes/GUIMaskedFlagButton.xml
  extension/doc_classes/GUINode.xml
  extension/doc_classes/GUIOverlappingElementsBox.xml
  extension/doc_classes/GUIPieChart.xml
  extension/doc_classes/GUIProgressBar.xml
  extension/doc_classes/GUIScrollbar.xml
  extension/doc_classes/GUITextureRect.xml
  extension/doc_classes/GameSingleton.xml
  extension/doc_classes/LoadLocalisation.xml
  extension/doc_classes/MapMesh.xml
  extension/doc_classes/MenuSingleton.xml
  extension/doc_classes/ModelSingleton.xml
  extension/doc_classes/SoundSingleton.xml
Labels: enhancement

#304 Add click masks to GameSession UI
  extension/src/openvic-extension/utility/UITools.cpp
  game/src/Game/GameSession/Ledger.gd
  game/src/Game/GameSession/Menubar.gd
  game/src/Game/GameSession/NationManagementScreen/BudgetMenu.gd
  game/src/Game/GameSession/NationManagementScreen/DiplomacyMenu.gd
  game/src/Game/GameSession/NationManagementScreen/MilitaryMenu.gd
  game/src/Game/GameSession/NationManagementScreen/PoliticsMenu.gd
  game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
  game/src/Game/GameSession/NationManagementScreen/ProductionMenu.gd
  game/src/Game/GameSession/NationManagementScreen/TechnologyMenu.gd
  game/src/Game/GameSession/NationManagementScreen/TradeMenu.gd
  game/src/Game/GameSession/SearchPanel.gd
  game/src/Game/GameSession/Topbar.gd
Labels: enhancement
