Repository OpenVicProject/OpenVic, pull requests merged in 2024-01, with the labels that each got.

#189 Maximum units per soldier POP & supply factor
  docs/simulation/calculations.yaml
Labels: documentation, enhancement

#194 Document <strata>_<need>_needs modifier effect
  docs/simulation/calculations.yaml
Labels: documentation, enhancement

#161 Add Basic Dataloding Documentation
  docs/dataloading-architecture.md
Labels: documentation, enhancement

#198 Add Victoria 2 Folder Picker dialog
  game/assets/localisation/locales/en_GB/menus.csv
  game/src/Game/Autoload/Argument/ArgumentParser.gd
  game/src/Game/GameStart.gd
  game/src/Game/GameStart.tscn
  game/src/Game/Menu/OptionMenu/ControlsTab.tscn
Labels: enhancement

#200 Update build workflow actions
  .github/workflows/builds.yml
Labels: enhancement, build
