Repository OpenVicProject/OpenVic, pull requests merged in 2025-01, with the labels that each got.

#252 Add cursor support
  extension/doc_classes/CursorSingleton.xml
  extension/src/openvic-extension/register_types.cpp
  extension/src/openvic-extension/singletons/CursorSingleton.cpp
  extension/src/openvic-extension/singletons/CursorSingleton.hpp
  extension/src/openvic-extension/singletons/SoundSingleton.cpp
  extension/src/openvic-extension/utility/Utilities.hpp
  game/project.godot
  game/src/Game/Autoload/CursorManager.gd
  game/src/Game/GameSession/GameSession.gd
  game/src/Game/GameSession/GameSessionMenu.gd
  game/src/Game/GameStart.gd
  game/src/Game/LoadingScreen.tscn
Labels: enhancement

#351 Correct rgo size documentation
  docs/simulation/calculations.yaml
Labels: documentation

#354 Fix deprecated upload artifact CI error
  .github/workflows/builds.yml
Labels: bug, meta

#361 Add support for inline flags in GUILabel
  extension/src/openvic-extension/classes/GFXMaskedFlagTexture.cpp
  extension/src/openvic-extension/classes/GUILabel.cpp
  extension/src/openvic-extension/classes/GUILabel.hpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
Labels: enhancement

#364 Fix typos xml ignore regex
  pyproject.toml
Labels: bug

#363 Add GUILineChart with examples in budget and trade charts
  extension/doc_classes/GUILineChart.xml
  extension/doc_classes/GUINode.xml
  extension/src/openvic-extension/classes/GUILineChart.cpp
  extension/src/openvic-extension/classes/GUILineChart.hpp
  extension/src/openvic-extension/classes/GUINode.cpp
  extension/src/openvic-extension/classes/GUINode.hpp
  extension/src/openvic-extension/register_types.cpp
  extension/src/openvic-extension/utility/UITools.cpp
  game/src/Game/GameSession/NationManagementScreen/TradeMenu.gd
  game/src/Game/GameSession/Topbar.gd
Labels: enhancement

#360 Add research and leadership topbar tooltips and start research example
  extension/src/openvic-extension/singletons/GameSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.hpp
  game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
  game/src/Game/GameSession/Topbar.gd
Labels: enhancement

#355 Add/improve RGO production and size tooltips
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  extension/src/openvic-extension/singletons/MilitaryMenu.cpp
  game/src/Game/GameSession/ProvinceOverviewPanel.gd
Labels: enhancement
