Repository OpenVicProject/OpenVic, pull requests merged in 2025-02, with the labels that each got.

#369 Set GUILineChart's mouse_filter to ignore
  extension/doc_classes/GUILineChart.xml
  extension/src/openvic-extension/classes/GUILineChart.cpp
Labels: enhancement

#368 Fix nullptr crash in `GUILabel::generate_lines_and_segments`
  extension/src/openvic-extension/classes/GUILabel.cpp
Labels: bug, crash

#371 Add MapView to LobbyMenu
  game/src/Game/GameMenu.tscn
  game/src/Game/GameSession/GameSession.gd
  game/src/Game/GameSession/GameSession.tscn
  game/src/Game/GameSession/MapView.gd
  game/src/Game/Menu/LobbyMenu/LobbyMenu.gd
  game/src/Game/Menu/LobbyMenu/LobbyMenu.tscn
Labels: enhancement

#372 Add escape back shortcut to LobbyMenu
  game/src/Game/Menu/LobbyMenu/LobbyMenu.gd
  game/src/Game/Menu/LobbyMenu/LobbyMenu.tscn
Labels: enhancement

#374 Document gold rgo income
  docs/simulation/calculations.yaml
Labels: documentation

#379 Fixed scene ids being considered for spelling
  pyproject.toml
Labels: bug

#346 Add multiplayer menu
  game/assets/localisation/locales/en_GB/menus.csv
  game/project.godot
  game/src/Game/Autoload/Events.gd
  game/src/Game/Autoload/Events/Multiplayer.gd
  game/src/Game/GameMenu.gd
  game/src/Game/GameMenu.tscn
  game/src/Game/Menu/LobbyMenu/LobbyMenu.gd
  game/src/Game/Menu/MainMenu/MainMenu.gd
  game/src/Game/Menu/MultiplayerMenu/ConnectionFailDialog.gd
  game/src/Game/Menu/MultiplayerMenu/DirectConnectionEntry.gd
  game/src/Game/Menu/MultiplayerMenu/DirectConnectionEntry.tscn
  game/src/Game/Menu/MultiplayerMenu/DirectConnectionTab.gd
  game/src/Game/Menu/MultiplayerMenu/DirectConnectionTab.tscn
  game/src/Game/Menu/MultiplayerMenu/HostTab.gd
  game/src/Game/Menu/MultiplayerMenu/HostTab.tscn
  game/src/Game/Menu/MultiplayerMenu/MultiplayerMenu.gd
  game/src/Game/Menu/MultiplayerMenu/MultiplayerMenu.tscn
  game/src/Game/Menu/MultiplayerMenu/PasswordDialog.gd
  game/src/Game/Menu/MultiplayerMenu/SecretEdit.gd
  game/src/Game/Menu/MultiplayerMenu/SecretEdit.tscn
  game/src/Game/Menu/SaveLoadMenu/SaveLoadMenu.gd
Labels: enhancement

#381 Move StyleBoxWithSound to C++ extension
  extension/doc_classes/StyleBoxWithSound.xml
  extension/src/openvic-extension/classes/resources/StyleBoxWithSound.cpp
  extension/src/openvic-extension/classes/resources/StyleBoxWithSound.hpp
  extension/src/openvic-extension/register_types.cpp
  game/assets/graphics/theme/game_session_menu.tres
  game/assets/graphics/theme/main_menu.tres
  game/src/Game/Theme/StyleBoxWithSound.gd
Labels: enhancement

#386 Use ProvinceInstance::get_index
  extension/src/openvic-extension/singletons/GameSingleton.cpp
  extension/src/openvic-extension/singletons/PopulationMenu.cpp
Labels: enhancement

#387 Use is_trading_good and get_good_data in TradeMenu.cpp
  extension/src/openvic-extension/singletons/TradeMenu.cpp
Labels: enhancement

#335 Add map projections
  extension/doc_classes/MapItemSingleton.xml
  extension/src/openvic-extension/singletons/AssetManager.cpp
  extension/src/openvic-extension/singletons/MapItemSingleton.cpp
  extension/src/openvic-extension/singletons/MapItemSingleton.hpp
  game/project.godot
  game/src/Game/GameSession/BillboardManager.gd
  game/src/Game/GameSession/MapView.gd
  game/src/Game/GameSession/MapView.tscn
  game/src/Game/GameSession/Projection.gdshader
  game/src/Game/GameSession/ProjectionManager.gd
  game/src/Game/GameSession/SelectionMarkers.gd
  game/src/Game/GameSession/ValidMoveMarkers.gd
Labels: enhancement

#395 Allow pie chart tooltip customisation and fix Population Menu over-scaling
  extension/src/openvic-extension/classes/GFXPieChartTexture.cpp
  extension/src/openvic-extension/classes/GFXPieChartTexture.hpp
  extension/src/openvic-extension/classes/GUIPieChart.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.hpp
  extension/src/openvic-extension/singletons/PopulationMenu.cpp
  game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
Labels: bug, enhancement

#396 Add GUIListBox sort_children function and use it in Trade and Military menus
  extension/doc_classes/GUIListBox.xml
  extension/doc_classes/MenuSingleton.xml
  extension/src/openvic-extension/classes/GUIListBox.cpp
  extension/src/openvic-extension/classes/GUIListBox.hpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.hpp
  extension/src/openvic-extension/singletons/MilitaryMenu.cpp
  game/src/Game/GameSession/NationManagementScreen/MilitaryMenu.gd
  game/src/Game/GameSession/NationManagementScreen/TradeMenu.gd
Labels: enhancement

#403 Social welfare is scaled by neither plurality nor consciousness
  docs/simulation/calculations.yaml
Labels: documentation

#407 Ensure rtti is always enabled
  SConstruct
Labels: bug
