Repository OpenVicProject/OpenVic, pull requests merged in 2025-03, with the labels that each got.

#414 Remove MapMesh request_update hack
  extension/src/openvic-extension/classes/MapMesh.cpp
  extension/src/openvic-extension/classes/MapMesh.hpp
Labels: bug

#415 Narrow the scope of class reference checks to xml files
  .github/workflows/builds.yml
Labels: bug

#416 Avoid having duplicate animations in library
  game/src/Game/GameSession/ModelManager.gd
  game/src/Game/Model/UnitModel.gd
Labels: bug

#419 Fix reductive SoundEffect lookup failure
  extension/src/openvic-extension/singletons/SoundSingleton.cpp
Labels: bug

#417 Replace load_godot_wav with `AudioStreamWAV::load_from_file`
  extension/src/openvic-extension/singletons/SoundSingleton.cpp
  extension/src/openvic-extension/singletons/SoundSingleton.hpp
Labels: enhancement

#418 Replace load_godot_mp3 with `AudioStreamMP3::load_from_file`
  extension/src/openvic-extension/singletons/SoundSingleton.cpp
  extension/src/openvic-extension/singletons/SoundSingleton.hpp
Labels: enhancement

#420 Fix divide by zero in RGO tooltip code for unpopulated states
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
Labels: bug

#426 Long issue identifiers
  extension/src/openvic-extension/classes/GFXPieChartTexture.hpp
  extension/src/openvic-extension/singletons/MenuSingleton.cpp
  extension/src/openvic-extension/singletons/MenuSingleton.hpp
  extension/src/openvic-extension/singletons/PopulationMenu.cpp
Labels: enhancement

#429 Add merge_group support to builds workflow
  .github/workflows/builds.yml
  .github/workflows/cache_cleanup.yml
Labels: bug, enhancement, meta

#430 Add Builds CI status badge to README
  README.md
Labels: enhancement
