Repository OpenVicProject/OpenVic, pull requests merged in 2025-08, with the labels that each got.

#535 Add dependabot PR labels automation
  .github/workflows/dependabot-labels.yml
Labels: enhancement, meta, dependencies

#547 Add vscode launch.json to gitignore
  .gitignore
Labels: bug, meta

#558 Fix GameStart not using first class Callables
  game/src/Systems/Startup/GameStart.gd
Labels: enhancement, topic:codestyle

#557 Update tab scenes' OptionButton item_counts
  game/src/UI/GameMenu/OptionMenu/GeneralTab.tscn
  game/src/UI/GameMenu/OptionMenu/VideoTab.tscn
Labels: bug, topic:gui, topic:codestyle

#560 Update make_rst.py's Godot version to 4.4.1
  extension/doc_tools/make_rst.py
  extension/doc_tools/patches/make_rst.patch
Labels: documentation, enhancement, meta

#559 Add editor embedded game window support
  game/src/Autoload/Resolution.gd
  game/src/Autoload/WindowOverride.gd
Labels: enhancement, topic:core
